# Generated by Django 2.1.5 on 2021-04-02 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='learning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_title', models.CharField(max_length=200)),
                ('learning_content', models.TextField()),
                ('learning_published', models.DateTimeField(default=datetime.datetime(2021, 4, 2, 13, 5, 25, 714543), verbose_name='date published')),
            ],
        ),
    ]
