# Generated by Django 2.1.5 on 2021-04-04 14:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210402_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='learningcatagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_catagory', models.CharField(max_length=200)),
                ('catagory_summary', models.CharField(max_length=200)),
                ('catagory_slug', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Catagories',
            },
        ),
        migrations.CreateModel(
            name='LearningSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_series', models.CharField(max_length=200)),
                ('series_summary', models.CharField(max_length=200)),
                ('learning_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.learningcatagory', verbose_name='Catagory')),
            ],
            options={
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.AddField(
            model_name='learning',
            name='learning_slug',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='learning',
            name='learning_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 4, 20, 15, 39, 374645), verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='learning',
            name='learning_series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.LearningSeries', verbose_name='Series'),
        ),
    ]
