# Generated by Django 2.1.5 on 2021-04-06 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210404_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learning',
            name='learning_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 6, 18, 2, 18, 824672), verbose_name='date published'),
        ),
    ]
