# Generated by Django 2.1.5 on 2021-04-06 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210406_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learning',
            name='learning_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 6, 19, 10, 25, 802449), verbose_name='date published'),
        ),
    ]
