# Generated by Django 2.1.4 on 2022-02-26 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210406_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learning',
            name='learning_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 26, 13, 37, 46, 933334), verbose_name='date published'),
        ),
    ]
