# Generated by Django 2.1.4 on 2022-02-26 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20220226_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learning',
            name='learning_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 26, 14, 7, 32, 469475), verbose_name='date published'),
        ),
    ]
