# Generated by Django 2.1.4 on 2022-02-26 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220226_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learning',
            name='learning_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 26, 14, 14, 31, 188574), verbose_name='date published'),
        ),
    ]
